#!/usr/bin/python
first_list = 0
second_list = 0
list = [1,2,3,2,12,3,21,2,2,3,4111,22,3333,444,111,4,5,777,65555,45,33,45]
for x in list:
    if first_list<x:
        first_list=x
for y in list:
    while second_list<y<first_list:
        second_list=y
print 'The first num is: %s' % frist_list
print 'The second num is: %S' % second_list
